# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22-slim AS builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY src ./src

RUN npm install


# Build the application
RUN npm run build

# Command will be provided by smithery.yaml
CMD ["node", "dist/index.js"]
