# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy all files into the container
COPY . .

# Install dependencies without running prepare script to avoid building without source files
RUN npm install --ignore-scripts

# Build the typescript files
RUN npm run build

# Expose a port if needed (optional)

# Start the MCP server
CMD ["node", "dist/src/index.js"]
